apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: ulak-system
  name: ulakcronjob
spec:
  schedule: "* * * * *" # At every minute.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ulakcronjob
            image: ubuntu:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello $HOSTNAME from the Kubernetes cluster
          restartPolicy: OnFailure

#
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
#