apiVersion: ulaksystem/v1
kind: TaskSpace
metadata:
  taskSet: 5
  cronSet: 5
spec:
  tasks:
    task1:
      name: System Task 1
      cron:
        cronJob: /task1.sh
        cronSchedule: "*/15 * * * *"
        logFile: /task1.log
      find:
        junk:
          workspace: /data
          timeStamp: -mmin
          timeArg: +5
          logFile: /junk.log
        delete:
          workspace: /data/*
          timeStamp: -mmin
          timeArg: +5
          excludeFolder: /data/vip
          excludeFiles: /data/vip/*
          operation: -delete
      tar:
        mode: -cvf
        file: /data/ulak.tar
        path: /data/vip
      rsync:
        args: --update -raz --progress --delete-before --human-readable
        logFile: /meta.log
        exclude: vip
        path: /data/
        remoteHost:
          ip: 172.17.0.3
          destPath: /dwh/
      smtp:
        rxMail: ulaksystem@gmail.com
        mailFormat:
          success: /umail/system_success.txt
          fail: /umail/system_fail.txt