apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ulak-system
  name: ulakpvc
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany