apiVersion: v1
kind: Pod
metadata:
  namespace: ulak-system
  name: ulakslavepod
  labels:
    name: ulakslavepod
spec:
  restartPolicy: OnFailure
  containers:
  - name: ulakslavepod
    image: ubuntu:latest
    command: ['sh', '-c', 'echo "[SLAVE] Hello, Kubernetes!" && 
      apt-get -y update && 
      apt-get -y install curl && 
      apt-get -y install openssh-server && 
      apt-get -y install rsync && 
      apt-get install -y cron && 
      apt-get install -y bcron && 
      service ssh start && 
      service cron start && 
      echo "[SLAVE] Status: Ready" && 
      sleep 9999999999d && wait']
    volumeMounts:
      - mountPath: /dwh
        name: datawarehouse
      - mountPath: /ssh-dir
        name: master-key
  volumes:
    - name: datawarehouse
      persistentVolumeClaim:
        claimName: ulakpvc
    - name: master-key
      persistentVolumeClaim:
        claimName: sshpvc