apiVersion: v1
kind: Pod
metadata:
  namespace: ulak-system
  name: ulakslavepod
  labels:
    name: ulakslavepod
spec:
  restartPolicy: OnFailure
  containers:
  - name: ulakslavepod
    image: ubuntu:latest
    command: ['sh', '-c', 'echo "[SLAVE] Hello, Kubernetes!" && 
      apt-get -y update && 
      apt-get -y install curl && 
      apt-get -y install openssh-server && 
      apt-get -y install rsync && 
      service ssh start && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/ssh_conf.sh --output ssh_conf.sh && 
      chmod +x ssh_conf.sh && 
      sh ssh_conf.sh && 
      service ssh restart && 
      mkdir ~/.ssh && 
      chmod 700 ~/.ssh && 
      touch ~/.ssh/authorized_keys && 
      chmod 600 ~/.ssh/authorized_keys && 
      cat /ssh-dir/id_rsa.pub >> /root/.ssh/authorized_keys && 
      service ssh restart && 
      service cron start && 
      service rsync start && 
      echo "[SLAVE] Status: Ready" && 
      sleep 9999999999d && wait']
    volumeMounts:
      - mountPath: /dwh
        name: datawarehouse
      - mountPath: /ssh-dir
        name: master-key
  volumes:
    - name: datawarehouse
      persistentVolumeClaim:
        claimName: ulakpvc
    - name: master-key
      persistentVolumeClaim:
        claimName: sshpvc