apiVersion: v1
kind: Pod
metadata:
  namespace: ulak-system
  name: ulakmasterpod
  labels:
    name: ulakmasterpod
spec:
  restartPolicy: OnFailure
  containers:
  - name: ulakmasterpod
    image: ubuntu:latest
    command: ['sh','-c', 'echo "[MASTER] Hello, Kubernetes!" && 
      apt-get -y update && 
      apt-get -y install curl && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/init.sh --output init.sh && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/mission --output mission && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/ulakmeta.sh --output ulakmeta.sh && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/ulakMetaV2.sh --output ulakMetaV2.sh && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/configs/system.yaml --output system.yaml && 
      chmod +x init.sh && 
      chmod +x ulakmeta.sh && 
      chmod +x ulakMetaV2.sh && 
      sh init.sh && 
      ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa && 
      cp /root/.ssh/id_rsa.pub /master-ssh-key-dir/ && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/configs/ssmtp.conf --output /etc/ssmtp/ssmtp.conf && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/mail/system_fail.txt --output /umail/system_fail.txt && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/mail/system_success.txt --output /umail/system_success.txt && 
      crontab /mission && 
      echo "[MASTER] Status: Ready" && 
      sleep 9999999999d && wait']
    volumeMounts:
      - mountPath: /master-ssh-key-dir
        name: master-ssh-key
  volumes:
    - name: master-ssh-key
      persistentVolumeClaim:
        claimName: sshpvc