apiVersion: v1
kind: Pod
metadata:
  namespace: ulak-system
  name: ulakmasterpod
  labels:
    name: ulakmasterpod
spec:
  restartPolicy: OnFailure
  containers:
  - name: ulakmasterpod
    image: ubuntu:latest
    command: ['sh','-c', 'echo "[MASTER] Hello, Kubernetes!" && 
      apt-get -y update && 
      apt-get -y install curl && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/init.sh --output init.sh && 
      chmod +x init.sh && 
      sh init.sh && 
      sleep 9999999999d && wait']