apiVersion: v1
kind: Pod
metadata:
  namespace: ulak-system
  name: ulakmasterpod
  labels:
    name: ulakmasterpod
spec:
  restartPolicy: OnFailure
  containers:
  - name: ulakmasterpod
    image: ubuntu:latest
    command: ['sh','-c', 'echo "[MASTER] Hello, Kubernetes!" && 
      apt-get -y update && 
      apt-get -y install curl && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/init.sh --output init.sh && 
      curl https://raw.githubusercontent.com/yuhannes/ULAK/main/ulaksystem/scripts/mission --output mission && 
      chmod +x init.sh && 
      sh init.sh && 
      ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa && 
      cp /root/.ssh/id_rsa.pub /master-ssh-key-dir/ && 
      echo "[MASTER] Status: Ready" && 
      sleep 9999999999d && wait']
    volumeMounts:
      - mountPath: /dwh
        name: datawarehouse
      - mountPath: /master-ssh-key-dir
        name: master-ssh-key
  volumes:
    - name: datawarehouse
      persistentVolumeClaim:
        claimName: ulakpvc
    - name: master-ssh-key
      persistentVolumeClaim:
        claimName: sshpvc