apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ulak-system
  name: ulakbackup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ulakbackup
  template:
    metadata:
      labels:
        app: ulakbackup
    spec:
      containers:
      - name: ulakbackup
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "while true; do echo Hello-Ubuntu [BACKUP]; sleep 15 ; done"]
        ports:
          - containerPort: 4000
