apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ulak-system
  name: ulakmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ulakmaster
  template:
    metadata:
      labels:
        app: ulakmaster
    spec:
      containers:
      - name: ulakmaster
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "while true; do echo Hello-Ubuntu; sleep 15 ; done"]
        ports:
          - containerPort: 22